-- MySQL Script generated by MySQL Workbench
-- 05/04/16 21:30:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rouge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rouge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rouge` DEFAULT CHARACTER SET utf8 ;
USE `rouge` ;

-- -----------------------------------------------------
-- Table `rouge`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`user` (
  `id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `display_name` VARCHAR(62) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `create_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC));


-- -----------------------------------------------------
-- Table `rouge`.`contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`contents` (
  `id` INT(10) UNSIGNED NOT NULL,
  `paperId` INT(10) UNSIGNED NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `body` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `paperId_idx` (`paperId` ASC),
  CONSTRAINT `contentsPaperId`
    FOREIGN KEY (`paperId`)
    REFERENCES `rouge`.`papers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rouge`.`papers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`papers` (
  `id` INT(10) UNSIGNED NOT NULL,
  `userId` INT(10) UNSIGNED NOT NULL,
  `contentId` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC),
  INDEX `contentId_idx` (`contentId` ASC),
  CONSTRAINT `papersUserId`
    FOREIGN KEY (`userId`)
    REFERENCES `rouge`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `papersContentId`
    FOREIGN KEY (`contentId`)
    REFERENCES `rouge`.`contents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rouge`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`tags` (
  `id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `tagscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rouge`.`paperTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`paperTags` (
  `id` INT(10) UNSIGNED NOT NULL,
  `paperId` INT(10) UNSIGNED NOT NULL,
  `tagId` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `paperId_idx` (`paperId` ASC),
  INDEX `tagId_idx` (`tagId` ASC),
  CONSTRAINT `paperTagsPaperId`
    FOREIGN KEY (`paperId`)
    REFERENCES `rouge`.`papers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `paperTagsTagId`
    FOREIGN KEY (`tagId`)
    REFERENCES `rouge`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rouge`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`stocks` (
  `id` INT(10) UNSIGNED NOT NULL,
  `userId` INT(10) UNSIGNED NOT NULL,
  `paperId` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC),
  INDEX `paperId_idx` (`paperId` ASC),
  CONSTRAINT `stocksUserId`
    FOREIGN KEY (`userId`)
    REFERENCES `rouge`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stocksPaperId`
    FOREIGN KEY (`paperId`)
    REFERENCES `rouge`.`papers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
