-- MySQL Script generated by MySQL Workbench
-- 05/05/16 16:55:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rouge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rouge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rouge` DEFAULT CHARACTER SET utf8 ;
USE `rouge` ;

-- -----------------------------------------------------
-- Table `rouge`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `display_name` VARCHAR(62) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `create_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC));


-- -----------------------------------------------------
-- Table `rouge`.`contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`contents` (
  `id` INT(10) UNSIGNED NOT NULL,
  `paper_id` INT(10) UNSIGNED NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `body` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `paperId_idx` (`paper_id` ASC),
  CONSTRAINT `contentsPaperId`
    FOREIGN KEY (`paper_id`)
    REFERENCES `rouge`.`papers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rouge`.`papers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`papers` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `content_id` INT(10) UNSIGNED NOT NULL,
  `is_published` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`user_id` ASC),
  INDEX `contentId_idx` (`content_id` ASC),
  CONSTRAINT `papersUserId`
    FOREIGN KEY (`user_id`)
    REFERENCES `rouge`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `papersContentId`
    FOREIGN KEY (`content_id`)
    REFERENCES `rouge`.`contents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rouge`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`tags` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rouge`.`paperTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`paperTags` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `paper_id` INT(10) UNSIGNED NOT NULL,
  `tag_id` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `paperId_idx` (`paper_id` ASC),
  INDEX `tagId_idx` (`tag_id` ASC),
  CONSTRAINT `paperTagsPaperId`
    FOREIGN KEY (`paper_id`)
    REFERENCES `rouge`.`papers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `paperTagsTagId`
    FOREIGN KEY (`tag_id`)
    REFERENCES `rouge`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rouge`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rouge`.`stocks` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `paper_id` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`user_id` ASC),
  INDEX `paperId_idx` (`paper_id` ASC),
  CONSTRAINT `stocksUserId`
    FOREIGN KEY (`user_id`)
    REFERENCES `rouge`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stocksPaperId`
    FOREIGN KEY (`paper_id`)
    REFERENCES `rouge`.`papers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
